# ============================================
# /etc/ipsec.conf — strongSwan IPsec Configuration
# TP Infrastructure Debian - Adam Ghazel
# ============================================

config setup
    charondebug="ike 2, knl 2, cfg 2"

conn site-a-to-site-b
    authby=secret
    left=192.168.1.1
    leftsubnet=10.1.0.0/24
    right=192.168.2.1
    rightsubnet=10.2.0.0/24
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    keyexchange=ikev2
    auto=start
    type=tunnel

conn site-a-to-site-c
    authby=secret
    left=192.168.1.1
    leftsubnet=10.1.0.0/24
    right=192.168.3.1
    rightsubnet=10.3.0.0/24
    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
    keyexchange=ikev2
    auto=start
    type=tunnel
